#!/bin/bash
# SSH Connection Helper Script

echo "🔑 SSH Connection Guide for Magistrala EC2 Instance"
echo "=================================================="
echo ""
echo "To connect to your EC2 instance:"
echo ""
echo "1. Open Terminal and navigate to Downloads folder:"
echo "   cd ~/Downloads"
echo ""
echo "2. Set proper permissions on the SSH key:"
echo "   chmod 400 magistrala-ssh-key.pem"
echo ""
echo "3. Connect to the EC2 instance:"
echo "   ssh -i magistrala-ssh-key.pem ec2-user@44.196.96.48"
echo ""
echo "4. Once connected, check deployment status:"
echo "   sudo docker ps"
echo "   sudo docker-compose -f /opt/magistrala/magistrala/docker-compose-prod.yml logs"
echo ""
echo "5. Check deployment script progress:"
echo "   sudo tail -f /var/log/cloud-init-output.log"
echo ""
echo "=================================================="